# Site settings
title: Justin Lee
description: > # this means to ignore newlines until "baseurl:"
  Justin Lee's Personal Blog Page 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://justinjameslee.github.io" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate]

# comments
disqus: # add disqus shortname here

# author info
# add your appropriate info here
author: Justin # your name
bio: Programmer and Gamer    # your bio
email: justinlee@legacytech.tk
email_md5: 90ec72d85fafcdb600d32999026b653d # md5 hash of your email
twitter_username: Legacy477
github_username: justinjameslee
disqus_shortname: justinjameslee

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
